# fly.toml app configuration file generated for annos on 2025-05-13T18:45:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'annos'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
NODE_ENV="dev"
ATPROTO_REDIRECT_URI="http://annos.fly.dev/api/users/oauth/callback"
BASE_URL="https://annos.fly.dev"
HOST="0.0.0.0"
APP_URL="https://annos.fly.dev"